name: Release
on:
  release:
    types: [prereleased, released]

jobs:
  release:
    name: Publish Plugin
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.release.tag_name }}

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v1.5.3

      # Publish the plugin
      - uses: actions/checkout@v1
      - name: Publish
        uses: ./.github/actions/pub-dev-publish
        with:
          credentials: ${{ secrets.CREDENTIALS_JSON }}
          dry_run: false
